.TH "C:/Users/hae19/source/repos/Pet-Calculator/Pet-Calc/ParserLibs/BaseElements.cs" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hae19/source/repos/Pet-Calculator/Pet-Calc/ParserLibs/BaseElements.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBPet_Calc\&.ParserLibs\&.BaseElements\fP"
.br
.RI "Базовый абстрактный класс "
.ti -1c
.RI "class \fBPet_Calc\&.ParserLibs\&.BaseOperand\fP"
.br
.RI "Абстрактный класс-наследник базового класса "
.ti -1c
.RI "class \fBPet_Calc\&.ParserLibs\&.BaseOperator\fP"
.br
.RI "Абстрактный класс-наследник базового класса "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBPet_Calc\fP"
.br
.ti -1c
.RI "namespace \fBPet_Calc\&.ParserLibs\fP"
.br
.RI "Набор классов для определения элементов выражения "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
