.TH "Содержание директории C:/Users/hae19/source/repos/Pet-Calculator" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/hae19/source/repos/Pet-Calculator
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBPet\-Calc\fP"
.br
.in -1c
