.TH "Содержание директории C:/Users/hae19/source/repos/Pet-Calculator/Pet-Calc/ParserLibs" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/hae19/source/repos/Pet-Calculator/Pet-Calc/ParserLibs
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBBaseElements\&.cs\fP"
.br
.ti -1c
.RI "файл \fBCalculator\&.cs\fP"
.br
.ti -1c
.RI "файл \fBOperands\&.cs\fP"
.br
.RI "Файл с классами-потомками от BaseOperand\&. "
.ti -1c
.RI "файл \fBOperators\&.cs\fP"
.br
.ti -1c
.RI "файл \fBParser\&.cs\fP"
.br
.ti -1c
.RI "файл \fBSimplifier\&.cs\fP"
.br
.ti -1c
.RI "файл \fBStringValidator\&.cs\fP"
.br
.in -1c
