.TH "C:/Users/hae19/source/repos/Pet-Calculator/Pet-Calc/ParserLibs/Operands.cs" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hae19/source/repos/Pet-Calculator/Pet-Calc/ParserLibs/Operands.cs \- Файл с классами-потомками от BaseOperand\&.  

.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBPet_Calc\&.ParserLibs\&.Number\fP"
.br
.RI "Класс, представляющий число в выражении "
.ti -1c
.RI "class \fBPet_Calc\&.ParserLibs\&.Variable\fP"
.br
.RI "Класс, представляющий переменную в выражении "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBPet_Calc\&.ParserLibs\fP"
.br
.RI "Набор классов для определения элементов выражения "
.ti -1c
.RI "namespace \fBPet_Calc\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Файл с классами-потомками от BaseOperand\&. 

С учётом сложившейся международной обстановки, повышение уровня гражданского сознания представляет собой интересный эксперимент проверки благоприятных перспектив\&. В своём стремлении повысить качество жизни, они забывают, что курс на социально-ориентированный национальный проект, а также свежий взгляд на привычные вещи — безусловно открывает новые горизонты для экспериментов, поражающих по своей масштабности и грандиозности\&. 
.PP
См\&. определение в файле \fBOperands\&.cs\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
