.TH "Pet_Calc.ParserLibs.Calculator" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.ParserLibs.Calculator
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBCalculator\fP (int value)"
.br
.ti -1c
.RI "string \fBCalc\fP (List< \fBBaseElements\fP > parsed)"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fB_numberCountAfterPoint\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBCalculator\&.cs\fP строка \fB6\fP
.SH "Конструктор(ы)"
.PP 
.SS "Pet_Calc\&.ParserLibs\&.Calculator\&.Calculator (int value)"

.PP
См\&. определение в файле \fBCalculator\&.cs\fP строка \fB66\fP
.SH "Методы"
.PP 
.SS "string Pet_Calc\&.ParserLibs\&.Calculator\&.Calc (List< \fBBaseElements\fP > parsed)"

.PP
См\&. определение в файле \fBCalculator\&.cs\fP строка \fB71\fP
.SH "Данные класса"
.PP 
.SS "int Pet_Calc\&.ParserLibs\&.Calculator\&._numberCountAfterPoint"

.PP
См\&. определение в файле \fBCalculator\&.cs\fP строка \fB8\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
