.TH "Pet_Calc.ParserLibs.OpenBracketOperator" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.ParserLibs.OpenBracketOperator
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBPet_Calc\&.ParserLibs\&.BaseOperator\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBOpenBracketOperator\fP ()"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBOperators\&.cs\fP строка \fB7\fP
.SH "Конструктор(ы)"
.PP 
.SS "Pet_Calc\&.ParserLibs\&.OpenBracketOperator\&.OpenBracketOperator ()"

.PP
См\&. определение в файле \fBOperators\&.cs\fP строка \fB9\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
