.TH "Pet_Calc.ParserLibs.Number" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.ParserLibs.Number \- Класс, представляющий число в выражении  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBPet_Calc\&.ParserLibs\&.BaseOperand\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBNumber\fP (double x)"
.br
.RI "Конструктор класса "
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.RI "Перегрузка оператора эквивалентности ==\&. "
.ti -1c
.RI "Exce override int \fBGetHashCode\fP ()"
.br
.RI "Перегрузка функции хеширования объекта "
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Подробное описание"
.PP 
Класс, представляющий число в выражении 

Не следует, однако забывать, что дальнейшее развитие различных форм деятельности способствует подготовки и реализации форм развития\&. Значимость этих проблем настолько очевидна, что консультация с широким активом играет важную роль в формировании новых предложений\&. С другой стороны рамки и место обучения кадров способствует подготовки и реализации модели развития\&. 
.PP
См\&. определение в файле \fBOperands\&.cs\fP строка \fB40\fP
.SH "Конструктор(ы)"
.PP 
.SS "Pet_Calc\&.ParserLibs\&.Number\&.Number (double x)"

.PP
Конструктор класса 
.PP
\fBАргументы\fP
.RS 4
\fIx\fP значение числа 
.RE
.PP

.PP
См\&. определение в файле \fBOperands\&.cs\fP строка \fB46\fP
.SH "Методы"
.PP 
.SS "override bool Pet_Calc\&.ParserLibs\&.Number\&.Equals (object obj)"

.PP
Перегрузка оператора эквивалентности ==\&. 
.PP
\fBАргументы\fP
.RS 4
\fIobj\fP объект, стоящий справа от оператора, передается в функцию 
.RE
.PP
\fBИсключения\fP
.RS 4
\fIException\fP Базовое исключение 
.RE
.PP
\fBВозвращает\fP
.RS 4
Возвращает bool значение 
.RE
.PP

.PP
См\&. определение в файле \fBOperands\&.cs\fP строка \fB57\fP
.SS "Exce override int Pet_Calc\&.ParserLibs\&.Number\&.GetHashCode ()"

.PP
Перегрузка функции хеширования объекта 
.PP
\fBВозвращает\fP
.RS 4
Возвращает хеш-код от int 
.RE
.PP

.PP
См\&. определение в файле \fBOperands\&.cs\fP строка \fB69\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
