.TH "Pet_Calc.Program" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.Program
.SH SYNOPSIS
.br
.PP
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBProgram\&.cs\fP строка \fB22\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
