.TH "Pet_Calc.ParserLibs.BaseElements" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.ParserLibs.BaseElements \- Базовый абстрактный класс  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBPet_Calc\&.ParserLibs\&.BaseOperand\fP и \fBPet_Calc\&.ParserLibs\&.BaseOperator\fP\&.
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "object \fBvalue\fP"
.br
.RI "поле объект, нужное для дальнейшего наследования и удобного хранения в коллекциях\&. Например, если у нас есть класс Car, который наследуется от класса Vehicle\&. Тогда, при поиске по Car мы можем обратиться к Vehicle, чтобы получить всю информацию о нем\&. В случае с объектами, нужно передать адрес объекта, чтобы вызвать метод GetClass ()\&. В C# нет наследования\&. Это означает, что каждый объект имеет свой собственный уникальный адрес, и нет возможности обратиться к нему по имени\&. Но существует множество способов сделать это\&. Один из таких способов - это использование ссылок\&. "
.in -1c
.SH "Подробное описание"
.PP 
Базовый абстрактный класс 

Также как высококачественный прототип будущего проекта предоставляет широкие возможности для новых предложений\&. Лишь базовые сценарии поведения пользователей своевременно верифицированы\&. 
.PP
См\&. определение в файле \fBBaseElements\&.cs\fP строка \fB7\fP
.SH "Данные класса"
.PP 
.SS "object Pet_Calc\&.ParserLibs\&.BaseElements\&.value"

.PP
поле объект, нужное для дальнейшего наследования и удобного хранения в коллекциях\&. Например, если у нас есть класс Car, который наследуется от класса Vehicle\&. Тогда, при поиске по Car мы можем обратиться к Vehicle, чтобы получить всю информацию о нем\&. В случае с объектами, нужно передать адрес объекта, чтобы вызвать метод GetClass ()\&. В C# нет наследования\&. Это означает, что каждый объект имеет свой собственный уникальный адрес, и нет возможности обратиться к нему по имени\&. Но существует множество способов сделать это\&. Один из таких способов - это использование ссылок\&. 
.PP
См\&. определение в файле \fBBaseElements\&.cs\fP строка \fB9\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
