.TH "Pet_Calc.ParserLibs.Simplifier" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.ParserLibs.Simplifier
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBSimplifier\fP ()"
.br
.ti -1c
.RI "string \fBPutMinusInBrackets\fP (string expr)"
.br
.ti -1c
.RI "string \fBSimplify\fP (string expression)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBSimplifier\&.cs\fP строка \fB7\fP
.SH "Конструктор(ы)"
.PP 
.SS "Pet_Calc\&.ParserLibs\&.Simplifier\&.Simplifier ()"

.PP
См\&. определение в файле \fBSimplifier\&.cs\fP строка \fB40\fP
.SH "Методы"
.PP 
.SS "string Pet_Calc\&.ParserLibs\&.Simplifier\&.PutMinusInBrackets (string expr)"

.PP
См\&. определение в файле \fBSimplifier\&.cs\fP строка \fB45\fP
.SS "string Pet_Calc\&.ParserLibs\&.Simplifier\&.Simplify (string expression)"

.PP
См\&. определение в файле \fBSimplifier\&.cs\fP строка \fB112\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
