.TH "Pet_Calc.ParserLibs.Parser" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.ParserLibs.Parser
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBParser\fP ()"
.br
.ti -1c
.RI "List< \fBBaseElements\fP > \fBParse\fP (string expression)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBParser\&.cs\fP строка \fB8\fP
.SH "Конструктор(ы)"
.PP 
.SS "Pet_Calc\&.ParserLibs\&.Parser\&.Parser ()"

.PP
См\&. определение в файле \fBParser\&.cs\fP строка \fB159\fP
.SH "Методы"
.PP 
.SS "List< \fBBaseElements\fP > Pet_Calc\&.ParserLibs\&.Parser\&.Parse (string expression)"

.PP
См\&. определение в файле \fBParser\&.cs\fP строка \fB165\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
