.TH "Pet_Calc.ParserLibs.StringValidator" 3 "Ср 26 Окт 2022" "Pet-Calculator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pet_Calc.ParserLibs.StringValidator
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBStringValidator\fP ()"
.br
.ti -1c
.RI "void \fBFixMultipleOperatorBetweenNumberAndBracket\fP (ref string value)"
.br
.ti -1c
.RI "bool \fBCheckBracketsCorrectNotation\fP (string str)"
.br
.ti -1c
.RI "bool \fBCheckCorrectOperatorsNotation\fP (string str)"
.br
.ti -1c
.RI "bool \fBValidate\fP (ref string str)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBStringValidator\&.cs\fP строка \fB8\fP
.SH "Конструктор(ы)"
.PP 
.SS "Pet_Calc\&.ParserLibs\&.StringValidator\&.StringValidator ()"

.PP
См\&. определение в файле \fBStringValidator\&.cs\fP строка \fB15\fP
.SH "Методы"
.PP 
.SS "bool Pet_Calc\&.ParserLibs\&.StringValidator\&.CheckBracketsCorrectNotation (string str)"

.PP
См\&. определение в файле \fBStringValidator\&.cs\fP строка \fB39\fP
.SS "bool Pet_Calc\&.ParserLibs\&.StringValidator\&.CheckCorrectOperatorsNotation (string str)"

.PP
См\&. определение в файле \fBStringValidator\&.cs\fP строка \fB92\fP
.SS "void Pet_Calc\&.ParserLibs\&.StringValidator\&.FixMultipleOperatorBetweenNumberAndBracket (ref string value)"

.PP
См\&. определение в файле \fBStringValidator\&.cs\fP строка \fB20\fP
.SS "bool Pet_Calc\&.ParserLibs\&.StringValidator\&.Validate (ref string str)"

.PP
См\&. определение в файле \fBStringValidator\&.cs\fP строка \fB125\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Pet-Calculator из исходного текста\&.
